# Generated by Django 3.2.5 on 2021-07-26 21:45

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('external_id', models.UUIDField(db_column='ei', editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='n', max_length=30)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('camp', 'Camp'), ('airport', 'Airport'), ('heliport', 'Heliport'), ('spa', 'Spa'), ('viewpoint', 'Viewpoint'), ('architecture', 'Architecture'), ('museum', 'Museum'), ('park', 'Park'), ('ski', 'Ski'), ('sports_venue', 'Sports Venue'), ('activity', 'Activity')], db_column='t', max_length=20)),
                ('description', models.TextField(db_column='d', max_length=1000, null=True)),
                ('address', models.JSONField(db_column='a')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), db_column='ii', null=True, size=None)),
                ('price_category', models.IntegerField(choices=[(0, 'Free'), (1, 'Cheap'), (2, 'Affordable'), (3, 'Moderate'), (4, 'Expensive'), (5, 'Luxury')], db_column='p')),
                ('created', models.DateTimeField(db_column='c', default=datetime.datetime.utcnow)),
                ('live', models.BooleanField(db_column='l', default=True)),
                ('friendly_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), choices=[('kids', 'Kids'), ('disability', 'Disability'), ('pets', 'Pets')], db_column='ft', default=None, size=None)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['live'], name='places_plac_l_173762_idx'),
        ),
    ]
