# Generated by Django 3.2.5 on 2021-07-19 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_column='ei', editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_column='n', max_length=30)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('camp', 'Camp'), ('airport', 'Airport'), ('heliport', 'Heliport'), ('spa', 'Spa'), ('viewpoint', 'Viewpoint'), ('architecture', 'Architecture'), ('museum', 'Museum'), ('park', 'Park'), ('ski', 'Ski'), ('sports_venue', 'Sports Venue'), ('activity', 'Activity')], db_column='t', max_length=20)),
                ('description', models.TextField(db_column='d', max_length=1000, null=True)),
                ('address', models.JSONField(db_column='a')),
                ('images', models.JSONField(db_column='ii', null=True)),
                ('price_category', models.IntegerField(choices=[(0, 'Free'), (1, 'Cheap'), (2, 'Affordable'), (3, 'Moderate'), (4, 'Expensive'), (5, 'Luxury')], db_column='p')),
                ('created', models.DateTimeField(db_column='c', default=datetime.datetime.utcnow)),
                ('live', models.BooleanField(db_column='l', default=True)),
            ],
        ),
    ]
