version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/heritage-api2
    links:
      - db:postgres
    container_name: heritageapi_web_1
    depends_on:
      - db
    networks:
      - app-tier

  db:
    image: postgres:13.3
    container_name: heritageapi_db_1
    restart: always
    networks:
      - app-tier
    environment:
      POSTGRES_DATABASE: admin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - 54322:5432

networks:
  app-tier:
    driver: bridge
