version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/heritage-api2
    links:
      - db:mongodb
    container_name: heritageapi_web_1
    depends_on:
      - db
    networks:
      - app-tier

  db:
    image: mysql:5.7.22
    container_name: heritageapi_db_1
    restart: always
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

networks:
  app-tier:
    driver: bridge
